
services:
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - "9090:80"
    depends_on:
        - backend